// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';
import '@angular/compiler';
import '@angular/platform-server';
import 'rxjs';
import "jquery";
import 'tether';
import 'tether/dist/js/tether.js';
import 'bootstrap';
import 'font-awesome/css/font-awesome.css';
import 'bootstrap/dist/css/bootstrap.css';
